### ISSUE TITLE
Error while compiling epserver

### ISSUE THREAD

**Issue by ash995** [mtcp-stack/mtcp#301]
I get the following error after make.

make[2]: Entering directory /home/ashwin/mtcp/apps/example'
   CC epserver.c
cat: /usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/lib/ldflags.txt: No such file or directory
   LD epserver.o
../../mtcp//lib/libmtcp.a(memory_mgt.o): In function `MPCreate':
/home/ashwin/mtcp/mtcp/src/memory_mgt.c:169: undefined reference to `rte_socket_id'
/home/ashwin/mtcp/mtcp/src/memory_mgt.c:168: undefined reference to `rte_mempool_create'
../../mtcp//lib/libmtcp.a(memory_mgt.o): In function `rte_lcore_id':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_lcore.h:95: undefined reference to `per_lcore__lcore_id'
../../mtcp//lib/libmtcp.a(memory_mgt.o): In function `rte_mempool_ops_dequeue_bulk':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_mempool.h:520: undefined reference to `rte_mempool_ops_table'
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_mempool.h:520: undefined reference to `rte_mempool_ops_table'
../../mtcp//lib/libmtcp.a(memory_mgt.o): In function `rte_lcore_id':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_lcore.h:95: undefined reference to `per_lcore__lcore_id'
../../mtcp//lib/libmtcp.a(memory_mgt.o): In function `rte_mempool_ops_enqueue_bulk':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_mempool.h:543: undefined reference to `rte_mempool_ops_table'
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_mempool.h:543: undefined reference to `rte_mempool_ops_table'
../../mtcp//lib/libmtcp.a(memory_mgt.o): In function `MPDestroy':
/home/ashwin/mtcp/mtcp/src/memory_mgt.c:205: undefined reference to `rte_mempool_free'
../../mtcp//lib/libmtcp.a(memory_mgt.o): In function `MPGetFreeChunks':
/home/ashwin/mtcp/mtcp/src/memory_mgt.c:215: undefined reference to `rte_mempool_avail_count'
../../mtcp//lib/libmtcp.a(memory_mgt.o): In function `rte_mempool_get_ops':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_mempool.h:483: undefined reference to `__rte_panic'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `rte_mempool_ops_enqueue_bulk':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_mempool.h:543: undefined reference to `rte_mempool_ops_table'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `dpdk_load_module':
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:662: undefined reference to `rte_pktmbuf_init'
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:690: undefined reference to `rte_socket_id'
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:685: undefined reference to `rte_pktmbuf_pool_init'
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:685: undefined reference to `rte_mempool_create'
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:705: undefined reference to `rte_eth_dev_info_get'
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:716: undefined reference to `rte_eth_dev_configure'
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:729: undefined reference to `rte_eth_dev_socket_id'
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:728: undefined reference to `rte_eth_rx_queue_setup'
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:741: undefined reference to `rte_eth_dev_socket_id'
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:740: undefined reference to `rte_eth_tx_queue_setup'
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:749: undefined reference to `rte_eth_dev_start'
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:755: undefined reference to `rte_eth_promiscuous_enable'
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:759: undefined reference to `rte_eth_dev_flow_ctrl_get'
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:765: undefined reference to `rte_eth_dev_flow_ctrl_set'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `check_all_ports_link_status':
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:604: undefined reference to `rte_eth_link_get_nowait'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `rte_delay_ms':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/generic/rte_cycles.h:178: undefined reference to `rte_delay_us'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `dpdk_load_module':
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:789: undefined reference to `rte_mempool_lookup'
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:800: undefined reference to `rte_eth_dev_info_get'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `check_all_ports_link_status':
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:604: undefined reference to `rte_eth_link_get_nowait'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `dpdk_load_module':
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:743: undefined reference to `rte_exit'
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:732: undefined reference to `rte_exit'
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:791: undefined reference to `rte_exit'
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:718: undefined reference to `rte_exit'
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:694: undefined reference to `per_lcore__rte_errno'
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:694: undefined reference to `rte_exit'
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:751: undefined reference to `rte_exit'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `rte_lcore_id':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_lcore.h:95: undefined reference to `per_lcore__lcore_id'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `rte_mempool_ops_dequeue_bulk':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_mempool.h:520: undefined reference to `rte_mempool_ops_table'
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_mempool.h:520: undefined reference to `rte_mempool_ops_table'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `dpdk_send_pkts':
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:369: undefined reference to `rte_eth_stats_reset'
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:369: undefined reference to `rte_eth_devices'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `rte_lcore_id':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_lcore.h:95: undefined reference to `per_lcore__lcore_id'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `rte_mempool_ops_dequeue_bulk':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_mempool.h:520: undefined reference to `rte_mempool_ops_table'
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_mempool.h:520: undefined reference to `rte_mempool_ops_table'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `dpdk_send_pkts':
/home/ashwin/mtcp/mtcp/src/dpdk_module.c:351: undefined reference to `rte_eth_stats_get'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `rte_pktmbuf_prefree_seg':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_mbuf.h:1357: undefined reference to `per_lcore__lcore_id'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `rte_mempool_ops_enqueue_bulk':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_mempool.h:543: undefined reference to `rte_mempool_ops_table'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `rte_atomic16_set':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/generic/rte_atomic.h:220: undefined reference to `per_lcore__lcore_id'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `rte_lcore_id':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_lcore.h:95: undefined reference to `per_lcore__lcore_id'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `__mempool_generic_put':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_mempool.h:1171: undefined reference to `per_lcore__lcore_id'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `rte_mempool_ops_enqueue_bulk':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_mempool.h:543: undefined reference to `rte_mempool_ops_table'
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_mempool.h:543: undefined reference to `rte_mempool_ops_table'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `rte_lcore_id':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_lcore.h:95: undefined reference to `per_lcore__lcore_id'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `rte_mempool_ops_enqueue_bulk':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_mempool.h:543: undefined reference to `rte_mempool_ops_table'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `rte_eth_rx_burst':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_ethdev.h:2886: undefined reference to `rte_eth_devices'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `rte_pktmbuf_prefree_seg':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_mbuf.h:1357: undefined reference to `per_lcore__lcore_id'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `rte_mempool_ops_enqueue_bulk':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_mempool.h:543: undefined reference to `rte_mempool_ops_table'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `rte_lcore_id':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_lcore.h:95: undefined reference to `per_lcore__lcore_id'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `__mempool_generic_put':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_mempool.h:1171: undefined reference to `per_lcore__lcore_id'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `rte_mempool_ops_enqueue_bulk':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_mempool.h:543: undefined reference to `rte_mempool_ops_table'
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_mempool.h:543: undefined reference to `rte_mempool_ops_table'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `rte_atomic16_set':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/generic/rte_atomic.h:220: undefined reference to `per_lcore__lcore_id'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `rte_lcore_id':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_lcore.h:95: undefined reference to `per_lcore__lcore_id'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `rte_mempool_ops_enqueue_bulk':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_mempool.h:543: undefined reference to `rte_mempool_ops_table'
../../mtcp//lib/libmtcp.a(dpdk_module.o): In function `rte_mempool_get_ops':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_mempool.h:483: undefined reference to `__rte_panic'
../../mtcp//lib/libmtcp.a(core.o): In function `rte_get_master_lcore':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_lcore.h:107: undefined reference to `rte_eal_get_configuration'
../../mtcp//lib/libmtcp.a(core.o): In function `mtcp_create_context':
/home/ashwin/mtcp/mtcp/src/core.c:1341: undefined reference to `rte_eal_remote_launch'
/home/ashwin/mtcp/mtcp/src/core.c:1332: undefined reference to `lcore_config'
../../mtcp//lib/libmtcp.a(core.o): In function `rte_lcore_id':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_lcore.h:95: undefined reference to `per_lcore__lcore_id'
../../mtcp//lib/libmtcp.a(core.o): In function `rte_get_master_lcore':
/usr/src/dpdk-stable-17.11.0/x86_64-native-linuxapp-gcc/include/rte_lcore.h:107: undefined reference to `rte_eal_get_configuration'
../../mtcp//lib/libmtcp.a(core.o): In function `mtcp_destroy':
/home/ashwin/mtcp/mtcp/src/core.c:1656: undefined reference to `rte_eal_wait_lcore'
../../mtcp//lib/libmtcp.a(cpu.o): In function `mtcp_core_affinitize':
/home/ashwin/mtcp/mtcp/src/cpu.c:79: undefined reference to `rte_thread_set_affinity'
../../mtcp//lib/libmtcp.a(io_module.o): In function `SetNetEnv':
/home/ashwin/mtcp/mtcp/src/io_module.c:295: undefined reference to `ceil'
/home/ashwin/mtcp/mtcp/src/io_module.c:348: undefined reference to `rte_eal_init'
/home/ashwin/mtcp/mtcp/src/io_module.c:355: undefined reference to `rte_eth_dev_count'
/home/ashwin/mtcp/mtcp/src/io_module.c:366: undefined reference to `rte_eth_macaddr_get'
/home/ashwin/mtcp/mtcp/src/io_module.c:461: undefined reference to `eal_proc_type_detect'
collect2: error: ld returned 1 exit status
make[2]: *** [epserver] Error 1
make[2]: Leaving directory `/home/ashwin/mtcp/apps/example'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ashwin/mtcp'
make: *** [all] Error 2

I am working with dpdk version 17.11
